version: '3.9'

services:
  # DB service
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "7676:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

  # Keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak-authentication
    command: start-dev
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-database
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: true
    depends_on:
      - keycloak-database

  # Keycloak DB service
  keycloak-database:
    image: postgres:14-alpine
    container_name: keycloak-database
    ports:
      - "54333:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-data:/var/lib/postgresql/data

volumes:
  keycloak-data:
    driver: local